import type { Detection, Severity } from "@/lib/types";
import { dateLabel, timecode } from "@/lib/types";
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-7"><div>{eyebrow&&<div className="text-xs font-bold tracking-[.18em] uppercase text-primary mb-2">{eyebrow}</div>}<h1 className="text-3xl lg:text-4xl font-bold tracking-tight">{title}</h1><p className="text-base-content/60 mt-2 max-w-2xl">{description}</p></div>{action}</div>}
export function Panel({title,children,action,className=""}:{title?:string;children:React.ReactNode;action?:React.ReactNode;className?:string}){return <section className={`bg-base-100 rounded-2xl border border-base-300 shadow-sm p-5 lg:p-6 ${className}`}>{(title||action)&&<div className="flex items-center justify-between gap-4 mb-5"><h2 className="text-lg font-semibold">{title}</h2>{action}</div>}{children}</section>}
export function SeverityBadge({severity}:{severity:Severity}){const color:Record<Severity,string>={critical:"badge-error",high:"badge-warning",medium:"badge-info",low:"badge-success",measurement:"badge-neutral"};return <span className={`badge badge-sm ${color[severity]} badge-soft capitalize`}>{severity==="measurement"?"Queue metric":severity}</span>}
export function StatusBadge({status}:{status:Detection["status"]}){return <span className={`badge badge-sm capitalize ${status==="new"?"badge-primary badge-soft":status==="reviewed"?"badge-success badge-soft":"badge-ghost"}`}>{status}</span>}
export function EventLabel({d}:{d:Detection}){return <span>{d.severity==="measurement"?d.category:`Suspected ${d.category.toLowerCase()}`}</span>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="text-center py-12 px-4"><div className="text-lg font-semibold">{title}</div><p className="text-base-content/60 mt-2 mb-5">{description}</p>{action}</div>}
export function EventTime({seconds}:{seconds:number}){return <span className="font-mono tabular-nums">{timecode(seconds)}</span>}
export function RecordedDate({value}:{value:string}){return <span>{dateLabel(value)}</span>}
