"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, Maximize2, MessageCircle, Pencil, Play, Send, X } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { EmptyState, EventLabel, EventTime, PageTitle, Panel, SeverityBadge, StatusBadge } from "@/components/ui";
import { demoAssistantService } from "@/lib/demo";
import { timecode, type AssistantReply, type Detection, type VideoRecord } from "@/lib/types";
function Assistant({video,onSeek}:{video:VideoRecord;onSeek:(s:number)=>void}){const [question,setQuestion]=useState("");const [reply,setReply]=useState<AssistantReply|null>(null);const [busy,setBusy]=useState(false);async function ask(){if(!question.trim())return;setBusy(true);try{setReply(await demoAssistantService.respond(video,question.trim()))}finally{setBusy(false)}}return <Panel title="Context assistant" action={<span className="badge badge-info badge-soft">Demo</span>}><p className="text-sm text-base-content/60 mb-4">Answers only from this recording&apos;s simulated annotations.</p><div className="flex gap-2"><input className="input w-full" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder="What happened in this recording?" aria-label="Ask assistant"/><button className="btn btn-primary" disabled={busy||!question.trim()} onClick={ask} aria-label="Send question"><Send size={17}/></button></div>{reply&&<div className="mt-4 rounded-xl bg-base-200 p-4 text-sm"><div className="flex items-center gap-2 font-semibold mb-2"><MessageCircle size={16}/>Demo response</div><p>{reply.text}</p><div className="flex flex-wrap gap-2 mt-3">{reply.references.map((r,i)=><button key={i} className="btn btn-xs btn-outline" onClick={()=>onSeek(r.seconds)}>{r.label} · {timecode(r.seconds)}</button>)}</div></div>}</Panel>}
export default function VideoReview(){const params=useParams<{id:string}>();const {videos,loading,alerts,notify,setReviewStatus,saveVideo}=useApp();const video=videos.find(v=>v.id===params.id);const player=useRef<HTMLVideoElement>(null);const frame=useRef<HTMLDivElement>(null);const previousTime=useRef(0);const [src,setSrc]=useState("");const [current,setCurrent]=useState(0);const [duration,setDuration]=useState(0);const [playError,setPlayError]=useState("");const [edit,setEdit]=useState(false);const [name,setName]=useState("");const [saveError,setSaveError]=useState("");
const mediaBlob=video?.blob, mediaPath=video?.mediaPath, mediaSource=video?.source;
useEffect(()=>{setName(video?.title??"")},[video?.title]);
useEffect(()=>{if(!mediaSource){setSrc("");return}if(mediaSource==="sample"){setSrc(mediaPath??"");return}if(!mediaBlob){setPlayError("This recording has no stored video file.");return}const url=URL.createObjectURL(mediaBlob);setSrc(url);return()=>URL.revokeObjectURL(url)},[mediaBlob,mediaPath,mediaSource]);
useEffect(()=>{const t=new URLSearchParams(window.location.search).get("t");if(t&&player.current){const seconds=Number(t);if(Number.isFinite(seconds)&&seconds>=0)player.current.currentTime=seconds}},[src]);
const seek=useCallback((seconds:number)=>{if(player.current){player.current.currentTime=seconds;setCurrent(seconds);player.current.play().catch(()=>{});player.current.scrollIntoView({behavior:"smooth",block:"center"})}},[]);
function onTime(time:number){setCurrent(time);if(video?.source==="sample"&&alerts&&time>=previousTime.current&&time-previousTime.current<2){const hit=video.detections.find(d=>d.status==="new"&&d.seconds>previousTime.current&&d.seconds<=time&&d.severity!=="measurement");if(hit)notify(`Recorded playback: ${hit.category} annotation at ${timecode(hit.seconds)}`)}previousTime.current=time}
async function rename(){if(!video||!name.trim())return;try{await saveVideo({...video,title:name.trim()});setEdit(false);setSaveError("")}catch(e){setSaveError(e instanceof Error?e.message:"Could not rename recording.")}}
if(loading)return <div className="loading loading-spinner text-primary"/>;
if(!video)return <EmptyState title="Recording not found" description="It may have been deleted from this browser." action={<Link href="/videos" className="btn btn-primary">Back to library</Link>}/>;
const active=video.detections.filter(d=>d.status!=="dismissed"&&Math.abs(d.seconds-current)<2&&d.box);
return <><Link href="/videos" className="link link-hover text-sm inline-flex gap-2 items-center mb-5"><ArrowLeft size={16}/>Video library</Link><PageTitle eyebrow={video.source==="sample"?"Simulated sample":"Local upload"} title={video.title} description={video.source==="sample"?"Recorded playback · detection annotations are simulated and require human review.":"Recorded playback · this upload has no detection analysis. Connect a detection service to generate annotations."} action={<button className="btn btn-outline" onClick={()=>setEdit(true)}><Pencil size={16}/>Rename</button>}/>
{edit&&<div className="mb-5 bg-base-100 rounded-xl p-4 border border-base-300 flex gap-2"><input className="input flex-1" value={name} onChange={e=>setName(e.target.value)} maxLength={120} aria-label="Recording name" onKeyDown={e=>{if(e.key==="Enter")rename()}}/><button className="btn btn-primary" onClick={rename} aria-label="Save name"><Check size={17}/></button><button className="btn btn-ghost" onClick={()=>setEdit(false)} aria-label="Cancel rename"><X size={17}/></button></div>}{saveError&&<div className="alert alert-error mb-4">{saveError}</div>}
<div className="grid xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,.8fr)] gap-6"><div className="space-y-6"><Panel><div ref={frame} className="video-frame"><div className="video-canvas" style={{"--video-ratio": duration && player.current?.videoHeight ? player.current.videoWidth / player.current.videoHeight : 16 / 9} as React.CSSProperties}><video ref={player} src={src} controls playsInline preload="metadata" onTimeUpdate={e=>onTime(e.currentTarget.currentTime)} onSeeked={e=>{previousTime.current=e.currentTarget.currentTime}} onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);const t=Number(new URLSearchParams(window.location.search).get("t"));if(t>0&&t<e.currentTarget.duration)e.currentTarget.currentTime=t}} onError={()=>setPlayError("The browser could not play this video. The file may be missing, damaged, or use an unsupported codec.")}/>{active.map(d=><div key={d.id} className="video-box" style={{left:`${d.box!.x*100}%`,top:`${d.box!.y*100}%`,width:`${d.box!.width*100}%`,height:`${d.box!.height*100}%`}}><span className="video-box-label">{d.box!.label}</span></div>)}</div></div>{playError&&<div role="alert" className="alert alert-error mt-4">{playError}</div>}
<div className="flex flex-wrap items-center justify-between gap-3 mt-5"><div className="flex items-center gap-3 text-sm"><span className="badge badge-info badge-soft">Recorded playback</span><span className="font-mono">{timecode(current)} / {timecode(duration||video.duration)}</span></div><div className="flex gap-2"><select className="select select-sm" aria-label="Playback speed" defaultValue="1" onChange={e=>{if(player.current)player.current.playbackRate=Number(e.target.value)}}><option value=".5">0.5×</option><option value="1">1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select><button className="btn btn-outline btn-sm" onClick={()=>frame.current?.requestFullscreen?.()}><Maximize2 size={15}/>Fullscreen</button></div></div>
<div className="mt-6"><div className="flex justify-between text-xs text-base-content/55 mb-2"><span>Timeline</span><span>{video.detections.length} annotations</span></div><div className="timeline-track" role="group" aria-label="Detection timeline">{video.detections.filter(d=>d.status!=="dismissed").map(d=><button key={d.id} className={`timeline-marker ${d.severity==="measurement"?"queue":""}`} style={{left:`${Math.min(98,Math.max(2,d.seconds/(duration||video.duration||1)*100))}%`}} onClick={()=>seek(d.seconds)} title={`${d.category} at ${timecode(d.seconds)}`} aria-label={`Seek to ${d.category} at ${timecode(d.seconds)}`}/>)}</div></div></Panel>
<Assistant video={video} onSeek={seek}/></div>
<div className="space-y-6"><Panel title="Detection timeline" action={<span className="badge badge-neutral badge-soft">{video.analysis==="demo"?"Simulated":"No analysis"}</span>}>{video.detections.length?<div className="space-y-3 max-h-[650px] overflow-y-auto">{[...video.detections].sort((a,b)=>a.seconds-b.seconds).map((d:Detection)=><div key={d.id} className={`rounded-xl border p-4 ${Math.abs(d.seconds-current)<2?"border-primary bg-primary/5":"border-base-300"}`}><div className="flex justify-between gap-2"><button className="font-mono font-semibold text-primary flex items-center gap-1" onClick={()=>seek(d.seconds)}><Play size={13}/><EventTime seconds={d.seconds}/></button><SeverityBadge severity={d.severity}/></div><div className="font-semibold mt-2"><EventLabel d={d}/></div><p className="text-sm text-base-content/60 mt-1">{d.description}</p><div className="flex flex-wrap items-center gap-2 mt-3"><StatusBadge status={d.status}/>{d.status!=="reviewed"&&<button className="btn btn-xs btn-outline" onClick={()=>setReviewStatus(video.id,d.id,"reviewed")}>Mark reviewed</button>}{d.status!=="dismissed"&&<button className="btn btn-xs btn-ghost" onClick={()=>setReviewStatus(video.id,d.id,"dismissed")}>Dismiss</button>}{d.status!=="new"&&<button className="btn btn-xs btn-ghost" onClick={()=>setReviewStatus(video.id,d.id,"new")}>Reset</button>}</div></div>)}</div>:<EmptyState title="No detections yet" description="The recording is ready to watch. Automated analysis needs a connected service."/>}</Panel></div></div></>}
