"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, Maximize2, MessageCircle, Pencil, Play, Send, Sparkles, X } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { EmptyState, EventLabel, EventTime, PageTitle, Panel, SeverityBadge, StatusBadge } from "@/components/ui";
import { demoAssistantService } from "@/lib/demo";
import { analyzeRecording, askAssistant, useModelStatus, type AnalysisProgress, type ModelStatus } from "@/lib/detection-client";
import type { ChatTurn } from "@/lib/vlm/assistant";
import { isScorerModel } from "@/lib/vlm/scorer";
import { timecode, type AssistantReply, type Detection, type VideoRecord } from "@/lib/types";
function Assistant({video,onSeek,model}:{video:VideoRecord;onSeek:(s:number)=>void;model:ModelStatus|null}){
 const live=!!model?.configured&&video.source==="upload";
 const [question,setQuestion]=useState("");const [turns,setTurns]=useState<(ChatTurn&{references?:AssistantReply["references"]})[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function ask(){const q=question.trim();if(!q)return;setBusy(true);setError("");setQuestion("");
  try{if(live){const history=[...turns,{role:"user" as const,content:q}];setTurns(history);const r=await askAssistant(video,history.map(({role,content})=>({role,content})));setTurns([...history,{role:"assistant",content:r.text,references:r.references}]);}
  else{const r=await demoAssistantService.respond(video,q);setTurns(t=>[...t,{role:"user",content:q},{role:"assistant",content:r.text,references:r.references}]);}}
  catch(e){setError(e instanceof Error?e.message:"The assistant could not answer.")}finally{setBusy(false)}}
 return <Panel title="Context assistant" action={<span className={`badge badge-soft ${live?"badge-primary":"badge-info"}`}>{live?"AI":"Demo"}</span>}>
  <p className="text-sm text-base-content/60 mb-4">{live?(video.analysis==="complete"?`Answers from this recording's AI analysis (${model?.chatModel??model?.model}). Detections are suspected until reviewed.`:"Run AI analysis first so the assistant has something to answer from."):"Answers only from this recording's simulated annotations."}</p>
  {turns.length>0&&<div className="space-y-3 mb-4 max-h-96 overflow-y-auto" aria-live="polite">{turns.map((t,i)=><div key={i} className={`rounded-xl p-3 text-sm ${t.role==="user"?"bg-primary/10 ml-8":"bg-base-200 mr-8"}`}>{t.role==="assistant"&&<div className="flex items-center gap-2 font-semibold mb-1"><MessageCircle size={15}/>{live?"Assistant":"Demo response"}</div>}<p className="whitespace-pre-wrap">{t.content.replace(/\*\*/g,"")}</p>{!!t.references?.length&&<div className="flex flex-wrap gap-2 mt-2">{t.references.map((r,j)=><button key={j} className="btn btn-xs btn-outline" onClick={()=>onSeek(r.seconds)}>{r.label===timecode(r.seconds)?r.label:`${r.label} · ${timecode(r.seconds)}`}</button>)}</div>}</div>)}</div>}
  <div className="flex gap-2"><input className="input w-full" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder={live?"What should I do about this incident?":"What happened in this recording?"} aria-label="Ask assistant"/><button className="btn btn-primary" disabled={busy||!question.trim()} onClick={ask} aria-label="Send question">{busy?<span className="loading loading-spinner loading-sm"/>:<Send size={17}/>}</button></div>
  {error&&<div role="alert" className="alert alert-error mt-3 text-sm">{error}</div>}
 </Panel>}

function AnalysisPanel({video,src,model,autoStart,onSaved}:{video:VideoRecord;src:string;model:ModelStatus|null;autoStart:boolean;onSaved:(v:VideoRecord)=>Promise<void>}){
 const [progress,setProgress]=useState<AnalysisProgress|null>(null);const [error,setError]=useState("");const abort=useRef<AbortController|null>(null);const started=useRef(false);
 const run=useCallback(async()=>{if(!src||abort.current)return;const ctrl=new AbortController();abort.current=ctrl;setError("");setProgress({done:0,total:0,failed:0});
  try{const out=await analyzeRecording(video,src,setProgress,ctrl.signal);await onSaved({...video,analysis:"complete",analysisModel:out.model,analysisError:out.failed?`${out.failed} window(s) could not be analysed.`:undefined,detections:out.detections,moments:out.moments});}
  catch(e){if(!ctrl.signal.aborted){const msg=e instanceof Error?e.message:"Analysis failed.";setError(msg);await onSaved({...video,analysis:"failed",analysisError:msg}).catch(()=>{})}}
  finally{abort.current=null;setProgress(null)}},[src,video,onSaved]);
 useEffect(()=>{if(autoStart&&model?.configured&&src&&!started.current&&video.analysis==="not_analyzed"){started.current=true;run()}},[autoStart,model,src,video.analysis,run]);
 useEffect(()=>()=>abort.current?.abort(),[]);
 if(video.source!=="upload")return null;
 const running=!!progress;const pct=progress&&progress.total?Math.round(progress.done/progress.total*100):0;
 return <Panel title="AI analysis" action={model?.configured?<span className="badge badge-soft badge-primary shrink-0">{model.provider}</span>:<span className="badge badge-soft badge-ghost shrink-0">Not connected</span>}>
  {!model?<div className="loading loading-spinner loading-sm"/>:!model.configured?<p className="text-sm text-base-content/65">No model is configured on the server. Set <code>VLM_BASE_URL</code> and <code>VLM_MODEL</code> in <code>webapp/.env.local</code> and restart the dev server.</p>:<>
   <p className="text-sm text-base-content/65 mb-4">{isScorerModel(model.model)?"Scores 8-second clips (16 frames at 2 fps, a new clip every 4 seconds) with the local shoplifting scorer, which answers only whether shoplifting happens in each clip. Results are suspected incidents that need human review.":"Samples 4 frames every 8 seconds and asks the model what happens in each window. Results are suspected incidents that need human review."}</p><p className="text-xs text-base-content/55 mb-4 break-all">Model: {model.model}{video.analysis==="complete"&&video.analysisModel&&video.analysisModel!==model.model?` · last run used ${video.analysisModel}`:""}</p>
   {running?<div><div className="flex justify-between text-sm mb-2"><span>Analysing window {Math.min(progress.done+1,progress.total||1)} of {progress.total||"…"}</span><span>{pct}%</span></div><progress className="progress progress-primary w-full" value={pct} max={100} aria-label="Analysis progress"/>{progress.failed>0&&<p className="text-xs text-warning mt-2">{progress.failed} window(s) failed and will be skipped.</p>}<button className="btn btn-sm btn-ghost mt-3" onClick={()=>abort.current?.abort()}>Cancel</button></div>
   :<button className="btn btn-primary" onClick={run} disabled={!src}><Sparkles size={16}/>{video.analysis==="complete"?"Re-run analysis":"Run AI analysis"}</button>}
   {video.analysisError&&!running&&<div role="alert" className={`alert mt-4 text-sm ${video.analysis==="failed"?"alert-error":"alert-warning"}`}>{video.analysis==="failed"?`Analysis failed: ${video.analysisError} Check the server log and model settings, then try again.`:video.analysisError}</div>}
   {error&&!video.analysisError&&<div role="alert" className="alert alert-error mt-4 text-sm">{error}</div>}
  </>}
 </Panel>}

function SceneLog({video,current,onSeek}:{video:VideoRecord;current:number;onSeek:(s:number)=>void}){
 if(!video.moments?.length)return null;
 return <Panel title="Scene log" action={<span className="badge badge-soft badge-neutral">{video.moments.length} windows</span>}><div className="space-y-1 max-h-80 overflow-y-auto">{video.moments.map(m=><button key={m.start} onClick={()=>onSeek(m.start)} className={`w-full text-left rounded-lg px-3 py-2 text-sm flex gap-3 hover:bg-base-200 ${current>=m.start&&current<m.end?"bg-primary/5":""}`}><EventTime seconds={m.start}/><span className="text-base-content/70">{m.summary||"No description"}</span></button>)}</div></Panel>}

export default function VideoReview(){const params=useParams<{id:string}>();const {videos,loading,alerts,notify,setReviewStatus,saveVideo}=useApp();const video=videos.find(v=>v.id===params.id);const player=useRef<HTMLVideoElement>(null);const frame=useRef<HTMLDivElement>(null);const previousTime=useRef(0);const [src,setSrc]=useState("");const [current,setCurrent]=useState(0);const [duration,setDuration]=useState(0);const [playError,setPlayError]=useState("");const [edit,setEdit]=useState(false);const [name,setName]=useState("");const [saveError,setSaveError]=useState("");const model=useModelStatus();const [autoAnalyze,setAutoAnalyze]=useState(false);
const mediaBlob=video?.blob, mediaPath=video?.mediaPath, mediaSource=video?.source;
useEffect(()=>{setName(video?.title??"")},[video?.title]);
useEffect(()=>{setAutoAnalyze(new URLSearchParams(window.location.search).get("analyze")==="1")},[]);
useEffect(()=>{if(!mediaSource){setSrc("");return}if(mediaSource==="sample"){setSrc(mediaPath??"");return}if(!mediaBlob){setPlayError("This recording has no stored video file.");return}const url=URL.createObjectURL(mediaBlob);setSrc(url);return()=>URL.revokeObjectURL(url)},[mediaBlob,mediaPath,mediaSource]);
useEffect(()=>{const t=new URLSearchParams(window.location.search).get("t");if(t&&player.current){const seconds=Number(t);if(Number.isFinite(seconds)&&seconds>=0)player.current.currentTime=seconds}},[src]);
const seek=useCallback((seconds:number)=>{if(player.current){player.current.currentTime=seconds;setCurrent(seconds);player.current.play().catch(()=>{});player.current.scrollIntoView({behavior:"smooth",block:"center"})}},[]);
function onTime(time:number){setCurrent(time);if(video?.source==="sample"&&alerts&&time>=previousTime.current&&time-previousTime.current<2){const hit=video.detections.find(d=>d.status==="new"&&d.seconds>previousTime.current&&d.seconds<=time&&d.severity!=="measurement");if(hit)notify(`Recorded playback: ${hit.category} annotation at ${timecode(hit.seconds)}`)}previousTime.current=time}
async function rename(){if(!video||!name.trim())return;try{await saveVideo({...video,title:name.trim()});setEdit(false);setSaveError("")}catch(e){setSaveError(e instanceof Error?e.message:"Could not rename recording.")}}
if(loading)return <div className="loading loading-spinner text-primary"/>;
if(!video)return <EmptyState title="Recording not found" description="It may have been deleted from this browser." action={<Link href="/videos" className="btn btn-primary">Back to library</Link>}/>;
const inRange=(d:Detection)=>current>=d.seconds-1.5&&current<=(d.endSeconds??d.seconds)+1.5;const active=video.detections.filter(d=>d.status!=="dismissed"&&inRange(d)&&d.box);
return <><Link href="/videos" className="link link-hover text-sm inline-flex gap-2 items-center mb-5"><ArrowLeft size={16}/>Video library</Link><PageTitle eyebrow={video.source==="sample"?"Simulated sample":"Local upload"} title={video.title} description={video.source==="sample"?"Recorded playback · detection annotations are simulated and require human review.":video.analysis==="complete"?`Recorded playback · AI-suspected incidents from ${video.analysisModel??"the model"}; each needs human review.`:"Recorded playback · this upload has no detection analysis yet. Run AI analysis to generate suspected incidents."} action={<button className="btn btn-outline" onClick={()=>setEdit(true)}><Pencil size={16}/>Rename</button>}/>
{edit&&<div className="mb-5 bg-base-100 rounded-xl p-4 border border-base-300 flex gap-2"><input className="input flex-1" value={name} onChange={e=>setName(e.target.value)} maxLength={120} aria-label="Recording name" onKeyDown={e=>{if(e.key==="Enter")rename()}}/><button className="btn btn-primary" onClick={rename} aria-label="Save name"><Check size={17}/></button><button className="btn btn-ghost" onClick={()=>setEdit(false)} aria-label="Cancel rename"><X size={17}/></button></div>}{saveError&&<div className="alert alert-error mb-4">{saveError}</div>}
<div className="grid xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,.8fr)] gap-6"><div className="space-y-6"><Panel><div ref={frame} className="video-frame"><div className="video-canvas" style={{"--video-ratio": duration && player.current?.videoHeight ? player.current.videoWidth / player.current.videoHeight : 16 / 9} as React.CSSProperties}><video ref={player} src={src||undefined} controls playsInline preload="metadata" onTimeUpdate={e=>onTime(e.currentTarget.currentTime)} onSeeked={e=>{previousTime.current=e.currentTarget.currentTime}} onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);const t=Number(new URLSearchParams(window.location.search).get("t"));if(t>0&&t<e.currentTarget.duration)e.currentTarget.currentTime=t}} onError={()=>setPlayError("The browser could not play this video. The file may be missing, damaged, or use an unsupported codec.")}/>{active.map(d=><div key={d.id} className="video-box" style={{left:`${d.box!.x*100}%`,top:`${d.box!.y*100}%`,width:`${d.box!.width*100}%`,height:`${d.box!.height*100}%`}}><span className="video-box-label">{d.box!.label}</span></div>)}</div></div>{playError&&<div role="alert" className="alert alert-error mt-4">{playError}</div>}
<div className="flex flex-wrap items-center justify-between gap-3 mt-5"><div className="flex items-center gap-3 text-sm"><span className="badge badge-info badge-soft">Recorded playback</span><span className="font-mono">{timecode(current)} / {timecode(duration||video.duration)}</span></div><div className="flex gap-2"><select className="select select-sm" aria-label="Playback speed" defaultValue="1" onChange={e=>{if(player.current)player.current.playbackRate=Number(e.target.value)}}><option value=".5">0.5×</option><option value="1">1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select><button className="btn btn-outline btn-sm" onClick={()=>frame.current?.requestFullscreen?.()}><Maximize2 size={15}/>Fullscreen</button></div></div>
<div className="mt-6"><div className="flex justify-between text-xs text-base-content/55 mb-2"><span>Timeline</span><span>{video.detections.length} {video.analysis==="complete"?"detections":"annotations"}</span></div><div className="timeline-track" role="group" aria-label="Detection timeline">{video.detections.filter(d=>d.status!=="dismissed").map(d=><button key={d.id} className={`timeline-marker ${d.severity==="measurement"?"queue":""} ${d.endSeconds?"range":""}`} style={d.endSeconds?{left:`${d.seconds/(duration||video.duration||1)*100}%`,width:`${Math.max(1.5,(d.endSeconds-d.seconds)/(duration||video.duration||1)*100)}%`}:{left:`${Math.min(98,Math.max(2,d.seconds/(duration||video.duration||1)*100))}%`}} onClick={()=>seek(d.seconds)} title={`${d.category} at ${timecode(d.seconds)}`} aria-label={`Seek to ${d.category} at ${timecode(d.seconds)}`}/>)}</div></div></Panel>
<Assistant video={video} onSeek={seek} model={model}/></div>
<div className="space-y-6"><AnalysisPanel video={video} src={src} model={model} autoStart={autoAnalyze} onSaved={saveVideo}/><Panel title="Detection timeline" action={<span className="badge badge-neutral badge-soft">{video.analysis==="demo"?"Simulated":video.analysis==="complete"?"AI · suspected":"No analysis"}</span>}>{video.detections.length?<div className="space-y-3 max-h-[650px] overflow-y-auto">{[...video.detections].sort((a,b)=>a.seconds-b.seconds).map((d:Detection)=><div key={d.id} className={`rounded-xl border p-4 ${inRange(d)?"border-primary bg-primary/5":"border-base-300"}`}><div className="flex justify-between gap-2"><button className="font-mono font-semibold text-primary flex items-center gap-1" onClick={()=>seek(d.seconds)}><Play size={13}/><EventTime seconds={d.seconds}/>{d.endSeconds&&<>–<EventTime seconds={d.endSeconds}/></>}</button><SeverityBadge severity={d.severity}/></div><div className="font-semibold mt-2"><EventLabel d={d}/></div><p className="text-sm text-base-content/60 mt-1">{d.description}</p>{d.confidence!=null&&<p className="text-xs text-base-content/50 mt-1">Model confidence {Math.round(d.confidence*100)}%</p>}<div className="flex flex-wrap items-center gap-2 mt-3"><StatusBadge status={d.status}/>{d.status!=="reviewed"&&<button className="btn btn-xs btn-outline" onClick={()=>setReviewStatus(video.id,d.id,"reviewed")}>Mark reviewed</button>}{d.status!=="dismissed"&&<button className="btn btn-xs btn-ghost" onClick={()=>setReviewStatus(video.id,d.id,"dismissed")}>Dismiss</button>}{d.status!=="new"&&<button className="btn btn-xs btn-ghost" onClick={()=>setReviewStatus(video.id,d.id,"new")}>Reset</button>}</div></div>)}</div>:<EmptyState title="No detections yet" description={video.analysis==="complete"?"The model found nothing suspicious in this recording. Watch the footage to confirm.":"The recording is ready to watch. Run AI analysis to look for suspected incidents."}/>}</Panel><SceneLog video={video} current={current} onSeek={seek}/></div></div></>}
