import { type Detection, type VideoRecord, categories, severityOrder, isSecurityDetection } from "./types";
export function allDetections(videos: VideoRecord[]) { return videos.flatMap(v=>v.detections.map(d=>({...d,videoTitle:v.title,recordedAt:v.recordedAt}))); }
export function counts(videos: VideoRecord[]) { const all=allDetections(videos); const active=all.filter(isSecurityDetection); return {videos:videos.length,detections:active.length,high:active.filter(d=>d.severity==="critical" || d.severity==="high").length,reviewed:active.filter(d=>d.status==="reviewed").length,measurements:all.filter(d=>d.severity==="measurement" && d.status!=="dismissed").length}; }
export function categoryChart(videos: VideoRecord[]) {const all=allDetections(videos).filter(d=>d.status!=="dismissed"); return categories.map(name=>({name,value:all.filter(d=>d.category===name).length})).filter(x=>x.value>0);}
export function severityChart(videos: VideoRecord[]) {const all=allDetections(videos).filter(d=>d.status!=="dismissed"); return severityOrder.map(name=>({name,value:all.filter(d=>d.severity===name).length})).filter(x=>x.value>0);}
export function videoChart(videos: VideoRecord[]) {return videos.map(v=>({name:v.title.replace(" · simulated",""),value:v.detections.filter(isSecurityDetection).length}));}
export function trendChart(videos: VideoRecord[]) {return [...new Set(videos.map(v=>v.recordedAt.slice(0,10)))].sort().map(date=>({date,value:videos.filter(v=>v.recordedAt.slice(0,10)===date).flatMap(v=>v.detections).filter(isSecurityDetection).length}));}
export function csvForDetections(rows: (Detection & {videoTitle:string;recordedAt:string})[]) {const cells=(items:(string|number)[])=>items.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(","); return [cells(["Video","Recorded at","Time (seconds)","Category","Severity","Status","Description"]),...rows.map(r=>cells([r.videoTitle,r.recordedAt,r.seconds,r.category,r.severity,r.status,r.description]))].join("\r\n");}
export function downloadCsv(rows: (Detection & {videoTitle:string;recordedAt:string})[]) {const blob=new Blob(["\uFEFF"+csvForDetections(rows)],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="kryptonxwatch-detections.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
