import type { VideoRecord, VideoRepository } from "./types";
const DB_NAME="kryptonxwatch"; const STORE="videos"; const VERSION=1;
function openDb(): Promise<IDBDatabase> { return new Promise((resolve,reject)=>{ const request=indexedDB.open(DB_NAME,VERSION); request.onupgradeneeded=()=>{ const db=request.result; if(!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE,{keyPath:"id"}); }; request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error ?? new Error("Could not open browser storage")); }); }
function transaction<T>(operation: (store: IDBObjectStore, done: (value:T)=>void, fail: (error:Error)=>void)=>void, mode: IDBTransactionMode): Promise<T> { return openDb().then(db=>new Promise<T>((resolve,reject)=>{ let value:T; let hasValue=false; const tx=db.transaction(STORE,mode); const store=tx.objectStore(STORE); const done=(result:T)=>{value=result;hasValue=true}; const fail=(error:Error)=>reject(error); tx.onerror=()=>reject(tx.error ?? new Error("Browser storage failed")); tx.onabort=()=>reject(tx.error ?? new Error("Browser storage transaction aborted")); tx.oncomplete=()=>{db.close();if(hasValue)resolve(value);else reject(new Error("Browser storage returned no result"))}; operation(store,done,fail); })); }
export const videoRepository: VideoRepository = {
 list:()=>transaction<VideoRecord[]>((store,done,fail)=>{const req=store.getAll();req.onsuccess=()=>done(req.result as VideoRecord[]);req.onerror=()=>fail(req.error ?? new Error("Could not load videos"));},"readonly"),
 save:(video)=>transaction<void>((store,done,fail)=>{const req=store.put(video);req.onsuccess=()=>done();req.onerror=()=>fail(req.error ?? new Error("Could not save video"));},"readwrite"),
 remove:(id)=>transaction<void>((store,done,fail)=>{const req=store.delete(id);req.onsuccess=()=>done();req.onerror=()=>fail(req.error ?? new Error("Could not delete video"));},"readwrite")
};
export function storageError(error: unknown): string { if(error instanceof DOMException && ["QuotaExceededError","NS_ERROR_DOM_QUOTA_REACHED"].includes(error.name)) return "Browser storage is full. Delete an existing recording or free space, then retry."; return error instanceof Error ? error.message : "Browser storage is unavailable. Check private browsing settings or available disk space."; }
