"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useApp } from "@/components/app-provider";
import { EmptyState, EventLabel, EventTime, Notice, PageTitle, Panel, SeverityBadge, StatusBadge } from "@/components/ui";
import { alertForDetection, type Alertable } from "@/lib/alert-client";
import { allDetections, downloadCsv } from "@/lib/analytics";
import { categories, dateLabel, severityOrder, type ReviewStatus } from "@/lib/types";
export default function Detections(){const {videos,setReviewStatus}=useApp();const [videoId,setVideoId]=useState("all");const [category,setCategory]=useState("all");const [severity,setSeverity]=useState("all");const [status,setStatus]=useState("all");const [sort,setSort]=useState("newest");const [error,setError]=useState("");const [alerting,setAlerting]=useState("");const [alertNote,setAlertNote]=useState<{tone:"info"|"error";text:string}|null>(null);
const rows=useMemo(()=>allDetections(videos).filter(d=>(videoId==="all"||d.videoId===videoId)&&(category==="all"||d.category===category)&&(severity==="all"||d.severity===severity)&&(status==="all"||d.status===status)).sort((a,b)=>sort==="oldest"?a.recordedAt.localeCompare(b.recordedAt)||a.seconds-b.seconds:sort==="severity"?severityOrder.indexOf(a.severity)-severityOrder.indexOf(b.severity):b.recordedAt.localeCompare(a.recordedAt)||b.seconds-a.seconds),[videos,videoId,category,severity,status,sort]);
async function update(video:string,id:string,next:ReviewStatus){try{await setReviewStatus(video,id,next)}catch(e){setError(e instanceof Error?e.message:"Could not update review status.")}}
// Texting the owner is a deliberate act here, one detection at a time; the
// server decides whether it is worth a message and whether the cap allows it.
async function alertOwner(d:Alertable&{videoTitle:string;source:"sample"|"upload"}){setAlerting(d.id);const r=await alertForDetection(d,d.videoTitle,d.source==="sample");setAlerting("");setAlertNote({tone:r.outcome==="sent"?"info":"error",text:r.message});}
return <><PageTitle eyebrow="Review queue" title="Detection log" description="Filter simulated annotations, open the matching video moment, and record your review decision." action={<button className="btn btn-outline" disabled={!rows.length} onClick={()=>downloadCsv(rows)}>Export filtered CSV</button>}/><Panel><div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3 mb-6"><select className="select w-full" value={videoId} onChange={e=>setVideoId(e.target.value)} aria-label="Filter recording"><option value="all">All recordings</option>{videos.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select><select className="select w-full" value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter category"><option value="all">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select className="select w-full" value={severity} onChange={e=>setSeverity(e.target.value)} aria-label="Filter severity"><option value="all">All severities</option>{severityOrder.map(x=><option key={x}>{x}</option>)}</select><select className="select w-full" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter review status"><option value="all">All statuses</option><option value="new">New</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option></select><select className="select w-full" value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort detections"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="severity">Severity</option></select></div>{error&&<div className="mb-4"><Notice tone="error" role="alert">{error}</Notice></div>}{alertNote&&<div className="mb-4"><Notice tone={alertNote.tone} role={alertNote.tone==="error"?"alert":undefined}>{alertNote.text}</Notice></div>}
{rows.length?<div className="overflow-x-auto"><table className="table"><thead><tr><th>Event</th><th>Recording</th><th>Time</th><th>Severity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><div className="font-medium"><EventLabel d={d}/></div><div className="text-xs text-base-content/55 max-w-64">{d.description}</div></td><td><Link className="link link-hover" href={`/videos/${d.videoId}?t=${d.seconds}`}>{d.videoTitle}</Link><div className="text-xs text-base-content/50">{dateLabel(d.recordedAt)}</div></td><td><Link href={`/videos/${d.videoId}?t=${d.seconds}`} className="link link-primary"><EventTime seconds={d.seconds}/></Link></td><td><SeverityBadge severity={d.severity}/></td><td><StatusBadge status={d.status}/></td><td className="whitespace-nowrap">{d.status!=="reviewed"&&<button className="btn btn-xs btn-outline mr-1" onClick={()=>update(d.videoId,d.id,"reviewed")}>Review</button>}{d.status!=="dismissed"&&<button className="btn btn-xs btn-ghost mr-1" onClick={()=>update(d.videoId,d.id,"dismissed")}>Dismiss</button>}{d.status!=="new"&&<button className="btn btn-xs btn-ghost mr-1" onClick={()=>update(d.videoId,d.id,"new")}>Reset</button>}{d.severity!=="measurement"&&<button className="btn btn-xs btn-ghost" disabled={alerting===d.id} onClick={()=>alertOwner(d)}>{alerting===d.id?"Sending…":"Alert owner"}</button>}</td></tr>)}</tbody></table></div>:<EmptyState title="No matching detections" description="Adjust the filters or open a sample recording to explore simulated annotations."/>}</Panel></>}
