"use client";
import Link from "next/link";
import { ArrowRight, Clapperboard, CloudUpload, Eye, ShieldAlert, Video } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { EmptyState, EventLabel, EventTime, PageTitle, Panel, SeverityBadge } from "@/components/ui";
import { allDetections, counts } from "@/lib/analytics";
import { dateLabel } from "@/lib/types";
export default function Dashboard(){const {videos,loading}=useApp();const stats=counts(videos);const recent=allDetections(videos).filter(d=>d.status!=="dismissed").sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt)||b.seconds-a.seconds).slice(0,5);const cards=[{label:"Recordings",value:stats.videos,icon:Video,color:"text-primary",href:"/videos"},{label:"Suspected incidents",value:stats.detections,icon:ShieldAlert,color:"text-warning",href:"/detections"},{label:"High priority",value:stats.high,icon:Eye,color:"text-error",href:"/detections?severity=high"},{label:"Reviewed",value:stats.reviewed,icon:Clapperboard,color:"text-success",href:"/detections?status=reviewed"}];
return <><PageTitle eyebrow="Security workspace" title="Overview" description="Review recorded footage, track suspected incidents, and keep your team focused on the moments that need attention." action={<Link href="/upload" className="btn btn-primary"><CloudUpload size={17}/>Upload video</Link>}/>
<div className="alert alert-info alert-soft mb-6 text-sm"><span><strong>Demo workspace:</strong> bundled recordings and detection annotations are simulated. Uploaded videos remain unanalyzed until a detection service is connected.</span></div>
<div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{cards.map(({label,value,icon:Icon,color,href})=><Link href={href} key={label} className="bg-base-100 border border-base-300 rounded-2xl p-5 hover:border-primary/50 transition-colors shadow-sm"><div className={`rounded-xl bg-base-200 w-fit p-2.5 ${color}`}><Icon size={22}/></div><div className="text-3xl font-bold mt-5">{loading?"—":value}</div><div className="text-sm text-base-content/60 mt-1">{label}</div></Link>)}</div>
<div className="grid xl:grid-cols-[1.6fr_1fr] gap-6"><Panel title="Recent detections" action={<Link href="/detections" className="link link-primary text-sm">View log <ArrowRight size={14} className="inline"/></Link>}>{recent.length?<div className="divide-y divide-base-300">{recent.map(d=><Link key={d.id} href={`/videos/${d.videoId}?t=${d.seconds}`} className="flex items-center gap-3 py-3 hover:bg-base-200/60 rounded-lg px-2"><div className="w-17 text-sm text-base-content/50"><EventTime seconds={d.seconds}/></div><div className="min-w-0 flex-1"><div className="font-medium truncate"><EventLabel d={d}/></div><div className="text-xs text-base-content/55 truncate">{d.videoTitle} · {dateLabel(d.recordedAt)}</div></div><SeverityBadge severity={d.severity}/></Link>)}</div>:<EmptyState title="No detections" description="Sample event annotations will appear here."/>}</Panel>
<Panel title="Recording library" action={<Link href="/videos" className="link link-primary text-sm">All recordings <ArrowRight size={14} className="inline"/></Link>}>{videos.slice(0,4).map(v=><Link key={v.id} href={`/videos/${v.id}`} className="flex items-center justify-between gap-3 py-3 border-b border-base-300 last:border-0 hover:text-primary"><div className="min-w-0"><div className="font-medium truncate">{v.title}</div><div className="text-xs text-base-content/55">{dateLabel(v.recordedAt)} · {v.detections.length} annotations</div></div><span className={`badge badge-sm ${v.source==="sample"?"badge-info badge-soft":"badge-neutral badge-soft"}`}>{v.source==="sample"?"Sample":"Upload"}</span></Link>)}{!videos.length&&<EmptyState title="No recordings" description="Upload a video to begin your local review." action={<Link href="/upload" className="btn btn-primary btn-sm">Upload video</Link>}/>}</Panel></div></>}
