"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Clapperboard, Search, Trash2, Upload } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { EmptyState, PageTitle, Panel } from "@/components/ui";
import { dateLabel, timecode } from "@/lib/types";
export default function Library(){const {videos,deleteVideo}=useApp();const [q,setQ]=useState("");const [source,setSource]=useState("all");const [sort,setSort]=useState("newest");const [error,setError]=useState("");const rows=useMemo(()=>videos.filter(v=>(source==="all"||v.source===source)&&[v.title,...v.detections.map(d=>d.description)].join(" ").toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="oldest"?a.recordedAt.localeCompare(b.recordedAt):b.recordedAt.localeCompare(a.recordedAt)),[videos,q,source,sort]);
async function remove(id:string,title:string){if(!window.confirm(`Delete "${title}" from this browser?`))return;try{await deleteVideo(id)}catch(e){setError(e instanceof Error?e.message:"Could not delete recording.")}}
return <><PageTitle eyebrow="Footage" title="Video library" description="Search, organize, and review locally saved recordings." action={<Link href="/upload" className="btn btn-primary"><Upload size={17}/>Upload video</Link>}/><Panel><div className="grid sm:grid-cols-[1fr_auto_auto] gap-3 mb-6"><label className="input w-full flex items-center gap-2"><Search size={17}/><input className="grow" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search names and annotations" aria-label="Search recordings"/></label><select className="select" value={source} onChange={e=>setSource(e.target.value)} aria-label="Filter source"><option value="all">All sources</option><option value="sample">Samples</option><option value="upload">Uploads</option></select><select className="select" value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort recordings"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></div>{error&&<div role="alert" className="alert alert-error mb-4">{error}</div>}
{rows.length?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{rows.map(v=><article key={v.id} className="rounded-xl border border-base-300 overflow-hidden hover:border-primary/40 transition-colors"><Link href={`/videos/${v.id}`} className="block aspect-video bg-gradient-to-br from-slate-800 to-slate-950 relative"><div className="absolute inset-0 flex items-center justify-center text-white/50"><Clapperboard size={42}/></div>{v.source==="sample"&&<video className="w-full h-full object-cover absolute inset-0" src={v.mediaPath} muted preload="metadata"/>}<span className="badge badge-sm absolute bottom-3 right-3">{timecode(v.duration)}</span></Link><div className="p-4"><div className="flex items-start justify-between gap-2"><Link href={`/videos/${v.id}`} className="font-semibold hover:text-primary line-clamp-1">{v.title}</Link><span className={`badge badge-sm shrink-0 ${v.source==="sample"?"badge-info badge-soft":"badge-neutral badge-soft"}`}>{v.source==="sample"?"Simulated":"Upload"}</span></div><p className="text-xs text-base-content/55 mt-2">{dateLabel(v.recordedAt)} · {v.detections.length} annotations</p><div className="mt-4 flex items-center justify-between"><Link href={`/videos/${v.id}`} className="btn btn-primary btn-sm">Review</Link><button className="btn btn-ghost btn-sm text-error" onClick={()=>remove(v.id,v.title)} aria-label={`Delete ${v.title}`}><Trash2 size={15}/>Delete</button></div></div></article>)}</div>:<EmptyState title="No matching recordings" description={videos.length?"Adjust your search or filters.":"Upload a recording to build your library."} action={!videos.length?<Link href="/upload" className="btn btn-primary">Upload video</Link>:undefined}/>}</Panel></>}
