"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useApp } from "@/components/app-provider";
import { EmptyState, EventLabel, PageTitle, Panel, SeverityBadge } from "@/components/ui";
import { allDetections, categoryChart, counts, downloadCsv, severityChart, trendChart, videoChart } from "@/lib/analytics";
import { dateLabel } from "@/lib/types";
const palette=["#2966d1","#05a898","#f0a235","#e15560","#8b70d6","#5b86a8","#c77a46","#40b477","#93a5ba"];
export default function Analytics(){const {videos}=useApp();const [sort,setSort]=useState("newest");const [category,setCategory]=useState("all");const stats=counts(videos);const byCategory=categoryChart(videos),bySeverity=severityChart(videos),byVideo=videoChart(videos),trend=trendChart(videos);const rows=useMemo(()=>allDetections(videos).filter(d=>d.status!=="dismissed"&&(category==="all"||d.category===category)).sort((a,b)=>sort==="oldest"?a.recordedAt.localeCompare(b.recordedAt)||a.seconds-b.seconds:sort==="severity"?["critical","high","medium","low","measurement"].indexOf(a.severity)-["critical","high","medium","low","measurement"].indexOf(b.severity):b.recordedAt.localeCompare(a.recordedAt)||b.seconds-a.seconds),[videos,sort,category]);const summary=stats.detections? `${stats.detections} suspected incidents across ${stats.videos} recordings; ${stats.high} high-priority and ${stats.reviewed} reviewed. ${stats.measurements} queue measurements are tracked separately. Results come from simulated sample annotations.`:"No suspected incidents are available. Uploads need a connected detection service before analytics can include findings.";
return <><PageTitle eyebrow="Recorded insights" title="Analytics" description="Explore annotation trends by recording date and export the current incident view." action={<button className="btn btn-outline" disabled={!rows.length} onClick={()=>downloadCsv(rows)}>Export filtered CSV</button>}/><div className="alert alert-info alert-soft mb-6"><span><strong>Demo summary:</strong> {summary}</span></div>
{!videos.length?<EmptyState title="No recordings" description="Add a recording to start building your workspace." action={<Link href="/upload" className="btn btn-primary">Upload video</Link>}/>:<><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{[{label:"Recordings",value:stats.videos},{label:"Suspected incidents",value:stats.detections},{label:"High priority",value:stats.high},{label:"Queue measurements",value:stats.measurements}].map(x=><div key={x.label} className="bg-base-100 border border-base-300 rounded-2xl p-5"><div className="text-sm text-base-content/60">{x.label}</div><div className="text-3xl font-bold mt-2">{x.value}</div></div>)}</div>
<div className="grid xl:grid-cols-2 gap-6 mb-6"><Panel title="Categories"><div className="chart-wrap">{byCategory.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={byCategory} layout="vertical" margin={{left:30,right:10}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={115} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="value" fill="#2966d1" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer>:<EmptyState title="No annotations" description="Charts appear when annotated samples are available."/>}</div></Panel>
<Panel title="Severity and queue metrics"><div className="chart-wrap">{bySeverity.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={bySeverity} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={55} outerRadius={85} label>{bySeverity.map((x,i)=><Cell key={x.name} fill={palette[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<EmptyState title="No annotations" description="No severity data yet."/>}</div><div className="flex flex-wrap justify-center gap-3 text-xs">{bySeverity.map((x,i)=><span key={x.name} className="capitalize"><span className="inline-block w-2 h-2 rounded-full mr-1" style={{background:palette[i]}}/>{x.name}: {x.value}</span>)}</div></Panel>
<Panel title="Suspected incidents by recording"><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={byVideo} margin={{left:0,right:10,bottom:20}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}} angle={-15} height={50}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#05a898" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
<Panel title="Trend by recording date"><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{left:0,right:10}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="value" stroke="#2966d1" strokeWidth={3} dot={{r:5}}/></LineChart></ResponsiveContainer></div></Panel></div>
<Panel title="Annotation details" action={<div className="flex gap-2"><select className="select select-sm" value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter analytics category"><option value="all">All categories</option>{byCategory.map(x=><option key={x.name}>{x.name}</option>)}</select><select className="select select-sm" value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort analytics rows"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="severity">Severity</option></select></div>}>{rows.length?<div className="overflow-x-auto"><table className="table"><thead><tr><th>Recording</th><th>Recorded</th><th>Event</th><th>Severity</th><th>Review</th></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><Link href={`/videos/${d.videoId}?t=${d.seconds}`} className="link link-primary">{d.videoTitle}</Link></td><td>{dateLabel(d.recordedAt)}</td><td><EventLabel d={d}/></td><td><SeverityBadge severity={d.severity}/></td><td className="capitalize">{d.status}</td></tr>)}</tbody></table></div>:<EmptyState title="No matching annotations" description="Try another category."/>}</Panel></>}</>}
