"use client";
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CloudUpload, FileVideo, Info, X } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { PageTitle, Panel } from "@/components/ui";
const maxBytes=250*1024*1024;
export default function UploadPage(){const router=useRouter();const {saveVideo}=useApp();const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [title,setTitle]=useState("");const [duration,setDuration]=useState(0);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [dragging,setDragging]=useState(false);const input=useRef<HTMLInputElement>(null);
useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
function choose(f?:File){setError("");setDuration(0);if(!f)return;if(!["video/mp4","video/webm"].includes(f.type)&&!/(\.mp4|\.webm)$/i.test(f.name)){setError("Choose an MP4 or WebM video.");return}if(f.size>maxBytes){setError("This file exceeds the 250 MB browser-storage limit. Choose a smaller recording.");return}setFile(f);setTitle(f.name.replace(/\.(mp4|webm)$/i,""));}
function drop(e:DragEvent){e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0]);}
async function save(){if(!file||!Number.isFinite(duration)||duration<=0){setError("The video cannot be played or its duration is unavailable. Try a browser-compatible MP4 or WebM file.");return}if(!title.trim()){setError("Enter a name for this recording.");return}setSaving(true);setError("");try{const id=crypto.randomUUID();await saveVideo({id,title:title.trim(),recordedAt:new Date().toISOString(),duration,source:"upload",analysis:"not_analyzed",blob:file,size:file.size,detections:[]});router.push(`/videos/${id}`)}catch(e){setError(e instanceof Error?e.message:"Could not save this video.")}finally{setSaving(false)}}
return <><PageTitle eyebrow="Add recording" title="Upload a video" description="Keep a local copy in this browser for playback and manual review."/>
<div className="grid xl:grid-cols-[1.4fr_.6fr] gap-6"><Panel><input ref={input} type="file" accept="video/mp4,video/webm,.mp4,.webm" className="sr-only" onChange={(e:ChangeEvent<HTMLInputElement>)=>choose(e.target.files?.[0])}/><div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={drop} className={`border-2 border-dashed rounded-2xl p-8 text-center transition-colors ${dragging?"border-primary bg-primary/10":"border-base-300 bg-base-200/50"}`}><CloudUpload className="mx-auto text-primary mb-4" size={36}/><div className="font-semibold text-lg">Drop a recording here</div><p className="text-base-content/60 text-sm mt-1 mb-5">MP4 or WebM · up to 250 MB</p><button className="btn btn-primary" onClick={()=>input.current?.click()}>Choose file</button></div>
{file&&<div className="mt-6"><div className="flex items-center justify-between gap-3 mb-4"><div className="flex gap-2 items-center min-w-0"><FileVideo size={18} className="text-primary"/><span className="truncate font-medium">{file.name}</span><span className="text-xs text-base-content/50 shrink-0">{(file.size/1024/1024).toFixed(1)} MB</span></div><button className="btn btn-ghost btn-sm btn-circle" aria-label="Remove selected file" onClick={()=>{setFile(null);setPreview("");if(input.current)input.current.value=""}}><X size={16}/></button></div><video className="w-full rounded-xl bg-black max-h-96" src={preview} controls preload="metadata" onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onError={()=>setError("This file cannot be played in your browser. Try another MP4 or WebM encoding.")}/><label className="fieldset mt-5"><span className="fieldset-legend">Recording name</span><input className="input w-full" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="e.g. Store entrance · 10:15"/></label><button className="btn btn-primary mt-5" disabled={saving||!duration} onClick={save}>{saving?"Saving…":"Save recording"}</button></div>}{error&&<div role="alert" className="alert alert-error mt-5">{error}</div>}</Panel>
<Panel title="How this works"><div className="space-y-5 text-sm text-base-content/65"><p>Video files are stored in this browser using IndexedDB. They are not uploaded to a server.</p><p>Uploaded recordings start with no detections. The detection model service is not connected in this release.</p><div className="alert alert-info alert-soft"><Info size={18}/><span>To explore incident timelines and analytics, open the clearly labeled sample recordings in the video library.</span></div></div></Panel></div></>}
